apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-highlightjs-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: checkbox
          name: enableThemeSideRender
          id: enableThemeSideRender
          label: 启用主题侧渲染
          help: 启用之后会自动渲染文章中的代码块，以及根据下面的页面匹配规则渲染代码块。取消勾选之后，此插件仅会在编辑器中渲染代码块。
          value: true
        - $formkit: repeater
          if: "$get(enableThemeSideRender).value"
          name: rules
          id: rules
          key: rules
          label: 页面匹配规则
          value: []
          children:
            - $formkit: text
              name: pathPattern
              label: 路径匹配
              value: ""
              validation: required
              help: 用于匹配页面路径的符合 Ant-style 的表达式 ，如：/archives/**，被匹配的页面将会被添加代码高亮功能
        - $formkit: select
          if: "$get(enableThemeSideRender).value"
          name: style
          label: 代码块高亮主题
          value: "default.min.css"
          options:
            - value: "a11y-dark.min.css"
              label: "A11y Dark (深色)"
            - value: "a11y-light.min.css"
              label: "A11y Light (浅色)"
            - value: "catppuccin-mocha.css"
              label: "Catppuccin Mocha (深色)"
            - value: "catppuccin-macchiato.css"
              label: "Catppuccin Macchiato (深色)"
            - value: "catppuccin-frappe.css"
              label: "Catppuccin Frappe (深色)"
            - value: "catppuccin-latte.css"
              label: "Catppuccin Latte (浅色)"
            - value: "gruvbox-material-dark.css"
              label: "Gruvbox Material Dark (深色)"
            - value: "gruvbox-material-light.css"
              label: "Gruvbox Material Light (浅色)"
            - value: "agate.min.css"
              label: "Agate (深色)"
            - value: "an-old-hope.min.css"
              label: "An Old Hope (深色)"
            - value: "androidstudio.min.css"
              label: "Android Studio (深色)"
            - value: "arduino-light.min.css"
              label: "Arduino Light (浅色)"
            - value: "arta.min.css"
              label: "Arta (深色)"
            - value: "ascetic.min.css"
              label: "Ascetic (浅色)"
            - value: "atom-one-dark-reasonable.min.css"
              label: "Atom One Dark Reasonable (深色)"
            - value: "atom-one-dark.min.css"
              label: "Atom One Dark (深色)"
            - value: "atom-one-light.min.css"
              label: "Atom One Light (浅色)"
            - value: "github-auto.min.css"
              label: "GitHub Auto (自适应)"
            - value: "brown-paper.min.css"
              label: "Brown Paper (浅色)"
            - value: "codepen-embed.min.css"
              label: "CodePen Embed (深色)"
            - value: "color-brewer.min.css"
              label: "Color Brewer (浅色)"
            - value: "dark.min.css"
              label: "Dark (深色)"
            - value: "default.min.css"
              label: "Default (浅色)"
            - value: "devibeans.min.css"
              label: "Devibeans (深色)"
            - value: "dracula.min.css"
              label: "Dracula (深色)"
            - value: "docco.min.css"
              label: "Docco (浅色)"
            - value: "far.min.css"
              label: "Far (浅色)"
            - value: "felipec.min.css"
              label: "Felipec (深色)"
            - value: "foundation.min.css"
              label: "Foundation (浅色)"
            - value: "github-dark-dimmed.min.css"
              label: "GitHub Dark Dimmed (深色)"
            - value: "github-dark.min.css"
              label: "GitHub Dark (深色)"
            - value: "github.min.css"
              label: "GitHub (浅色)"
            - value: "gml.min.css"
              label: "GML (浅色)"
            - value: "googlecode.min.css"
              label: "Google Code (浅色)"
            - value: "gradient-dark.min.css"
              label: "Gradient Dark (深色)"
            - value: "gradient-light.min.css"
              label: "Gradient Light (浅色)"
            - value: "grayscale.min.css"
              label: "Grayscale (浅色)"
            - value: "hybrid.min.css"
              label: "Hybrid (深色)"
            - value: "idea.min.css"
              label: "IDEA (浅色)"
            - value: "intellij-light.min.css"
              label: "IntelliJ Light (浅色)"
            - value: "ir-black.min.css"
              label: "IR Black (深色)"
            - value: "isbl-editor-dark.min.css"
              label: "ISBL Editor Dark (深色)"
            - value: "isbl-editor-light.min.css"
              label: "ISBL Editor Light (浅色)"
            - value: "kimbie-dark.min.css"
              label: "Kimbie Dark (深色)"
            - value: "kimbie-light.min.css"
              label: "Kimbie Light (浅色)"
            - value: "lightfair.min.css"
              label: "Lightfair (浅色)"
            - value: "lioshi.min.css"
              label: "Lioshi (深色)"
            - value: "magula.min.css"
              label: "Magula (浅色)"
            - value: "mono-blue.min.css"
              label: "Mono Blue (浅色)"
            - value: "monokai-sublime.min.css"
              label: "Monokai Sublime (深色)"
            - value: "monokai.min.css"
              label: "Monokai (深色)"
            - value: "night-owl.min.css"
              label: "Night Owl (深色)"
            - value: "nnfx-dark.min.css"
              label: "NNFX Dark (深色)"
            - value: "nnfx-light.min.css"
              label: "NNFX Light (浅色)"
            - value: "nord.min.css"
              label: "Nord (深色)"
            - value: "obsidian.min.css"
              label: "Obsidian (深色)"
            - value: "paraiso-dark.min.css"
              label: "Paraiso Dark (深色)"
            - value: "paraiso-light.min.css"
              label: "Paraiso Light (浅色)"
            - value: "pojoaque.min.css"
              label: "Pojoaque (深色)"
            - value: "purebasic.min.css"
              label: "PureBasic (浅色)"
            - value: "qtcreator-dark.min.css"
              label: "Qt Creator Dark (深色)"
            - value: "qtcreator-light.min.css"
              label: "Qt Creator Light (浅色)"
            - value: "rainbow.min.css"
              label: "Rainbow (深色)"
            - value: "routeros.min.css"
              label: "RouterOS (深色)"
            - value: "school-book.min.css"
              label: "School Book (浅色)"
            - value: "shades-of-purple.min.css"
              label: "Shades of Purple (深色)"
            - value: "srcery.min.css"
              label: "Srcery (深色)"
            - value: "stackoverflow-dark.min.css"
              label: "Stack Overflow Dark (深色)"
            - value: "stackoverflow-light.min.css"
              label: "Stack Overflow Light (浅色)"
            - value: "sunburst.min.css"
              label: "Sunburst (深色)"
            - value: "z-night-dark.min.css"
              label: "Tokyo Night Dark (深色)"
            - value: "tokyo-night-light.min.css"
              label: "Tokyo Night Light (浅色)"
            - value: "tomorrow-night-blue.min.css"
              label: "Tomorrow Night Blue (深色)"
            - value: "tomorrow-night-bright.min.css"
              label: "Tomorrow Night Bright (深色)"
            - value: "tomorrow.min.css"
              label: "Tomorrow (浅色)"
            - value: "vs2015.min.css"
              label: "Visual Studio 2015 (深色)"
            - value: "xcode.min.css"
              label: "Xcode (浅色)"
            - value: "xt256.min.css"
              label: "XT256 (深色)"
        - $formkit: checkbox
          if: "$get(enableThemeSideRender).value"
          label: 显示复制按钮
          value: false
          name: showCopyButton
